[package]
name = "whitebeam"
version = "0.0.3"
authors = ["noproto"]
edition = "2018"

[lib]
name = "whitebeam"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
yaml-rust = "0.4"

[target.'cfg(target_os = "linux")'.dependencies.libc]
version = "0.2"
default-features = false
