# General info
[package]
name = "whitebeam"
version = "0.0.4"
authors = ["noproto"]
edition = "2018"

# Build targets
[lib]
name = "whitebeam"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "whitebeam"
path = "src/main.rs"
required-features = ["binaries"]

# Cross-platform dependencies
[dependencies]
clap = { version = "2.33.0", optional = true }
warp = { version = "0.1.18", optional = true }
rusqlite = { version = "0.20.0", optional = true, features = ["bundled"] }

[features]
binaries = ["clap", "warp", "rusqlite"]

# Linux dependencies
[target.'cfg(target_os = "linux")'.dependencies.libc]
version = "0.2"
default-features = false
